name: montecarlo_tdtr

channels:
  - conda-forge

dependencies:
  - python=3.12
  - pip

  # Core Python tools
  - typer
  - loguru
  - tqdm
  - black
  - flake8
  - isort

  # Scientific stack
  - numpy
  - scipy
  - pandas
  - seaborn
  - opencv
  - numba

  - cuda-version=12.4
  - cuda-cudart
  - cupy
  
  - pip:
      # Project/dev dependencies
      - python-dotenv
      - coverage
      - Sphinx
      - click
      - monaco
      - -e .