name: montecarlo_tdtr
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - typer
  - loguru
  - tqdm
  - black
  - flake8
  - isort
  - cupy
  - numba
  - numpy
  - scipy
  - pandas
  - seaborn
  - opencv
  - ipython
  - jupyterlab
  - pip:
    - python-dotenv
    - coverage
    - Sphinx
    - click
    - -e .
    - monaco